# Generated by Django 3.2.4 on 2021-06-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210616_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desc_content',
            name='desc',
            field=models.CharField(max_length=100),
        ),
    ]
