# Generated by Django 3.2.4 on 2021-06-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_desc_mountain'),
    ]

    operations = [
        migrations.CreateModel(
            name='content_mountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
    ]
