# Generated by Django 3.2.4 on 2021-06-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_content_tools_desc_tools'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='content_tools',
            new_name='content_tool',
        ),
        migrations.RenameModel(
            old_name='desc_tools',
            new_name='desc_tool',
        ),
    ]
