# Generated by Django 3.2.4 on 2021-06-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20210616_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='cta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
