# Generated by Django 3.2.4 on 2021-06-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20210616_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title_cta',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
